Config = {}
Config.Target = {
	["Abnormal Trigger Reset Timing"] = 5000,
	["Community Service Trigger"] = "esx_communityservice:sendToCommunityService",
	["Community Maximum Amount"] = 200,
	["Sellect Mysql"] = "mysql-async", -- mysql-async or oxmysql or ghmattimysql
	["Webhook"] = "https://discord.com/api/webhooks/954717071072170064/CSv4P_ifpiHtOv-VH3mS26dUDBGNhUEme21zyaCIWEtCxkI-vUL7hZ0MEOixhoA7St8V",
	["Message"] = "You have been suspended from the server for cheating!"
}

Config.AmountTrigger = {
	{trigger ="esx_communityservicesex:sendToCommunityService", value = -1},
	{trigger = "esx_fueldelivery:pay", value = 1000},
	{trigger = "esx_carthief:pay", value = 1000},
	{trigger = "esx_godirtyjob:pay", value = 1000},
	{trigger = "esx_pizza:pay", value = 1000},
	{trigger = "esx_ranger:pay", value = 1000},
	{trigger = "esx_garbagejob:pay", value = 1000},
	{trigger = "esx_gopostaljob:pay", value = 1000},
	{trigger = "esx_slotmachine:sv:2", value = 1000},
	{trigger = "esx_dmvschool:pay", value = 1000},
	{trigger = "esx_tankerjob:pay", value = 1000},
	{trigger = "esx_uber:pay", value = 100},
	{trigger = "CarryPeople:sync", value = -1},
	{trigger = "cmg3_animations:sync", value = -1},
	{trigger = "cmg2_animationsCarry:sync", value = -1},
	{trigger = "esx-qalle-jail:prisonWorkReward", value = 30},
	{trigger = "esx_policejob:handcuff", value = -1}, 
	{trigger = "esx_policejob:drag", value = -1},
	{trigger = "esx_sheriffjob:drag", value = -1},
	{trigger = "esx_policejob:putInVehicle", value = -1},
	{trigger = "esx_sheriffjob:requestarrest", value = -1},
	{trigger = "esx_policejob:requestarrest", value = -1},
	{trigger = "esx_sheriffjob:handcuff", value = -1},
	{trigger = "esx_sheriffjob:putInVehicle", value = -1},
	{trigger = "AdminMenu:giveBank", value = 1000},
	{trigger = "AdminMenu:giveCash", value = 1000},
	{trigger = "LegacyFuel:PayFuel", value = 1000},
	{trigger = "esx_society:billing", value = 100000},
	{trigger = "js:jailuser", value = -1},
	{trigger = "esx_jail:sendToJail", value = -1},
	{trigger = "esx_jailer:sendToJail", value = -1}, 
	{trigger = "esx-qalle-jail:jailPlayer", value = -1},
	{trigger = "esx_communityservice:sendToCommunityService", value = -1},
	{trigger = "3c98dea34ba8c14eea839a5d9b6e5d15:jailPlayer", value = -1},
	{trigger = "m3:shoprobbery:giveMoney", value = 1000},
	{trigger = "houseRobberies:giveMoney", value = 1000},
	{trigger = "t1ger_mechanicjob:JobReward", value = 1000},
	{trigger = "fonzillo,deep_hacker:giveMoney", value = 1000},
	{trigger = "esx_kazikazan:withdraw", value = 1000},
	{trigger = "sametk:hapispara", value = 100000},
	{trigger = "t1ger_deliveryjob:retrievePaycheck", value = 1000},
	{trigger = "wiro_miner:paraver", value = 1000},
	{trigger = "edz-cashdeskrob:giveMoney", value = 1000},
	{trigger = "esx-chopshop:addCash", value = 1000},
	{trigger = "utk_fh:rewardCash", value = 1000},
	{trigger = "utk_oh:rewardCash", value = 1000},
	{trigger = "esx_moneywash:deposit", value = 1000},
	{trigger = "esx_truckerjob:pay", value = 1000},
	{trigger = "esx_moneywash:withdraw", value = 1000}, 
	{trigger = "wiz:reward", value = 1000},
	{trigger = "esx_barbershop:pay", value = 100},
	{trigger = "norp-fleeca:rewardCash", value = 1000},
	{trigger = "esx_kekke_tackle:tryTackle", value = -1},
	{trigger = "esx_policejob:putInVehicle", value = -1},
	{trigger = "esx_policejob:OutVehicle", value = -1},
	{trigger = "DiscordBot:playerDied", value = -1}, 
	}

Config.Abnormal = {
		["InteractSound_SV:PlayWithinDistance"] = 3,
		["gcPhone:transfer"] = 5,
		["esx_policejob:billPlayer"] = 20,
		["esx_policejob:handcuff"] = 20,
		["esx_sheriffjob:requestarrest"] = 10,
		["InteractSound_SV:PlayOnAl"] = 50,
		["esx_fbijob:handcuff"] = 20,
		["cmg3_animations:sync"] = 5,
		["esx_communityservicesex:sendToCommunityService"] = 15,
		["esx_communityservice:sendToCommunityService"] = 15,
		["chat:server:ServerPSA"] = 2,
		["cmg2_animationsCarry:sync"] = 5,
		["gcPhone:sendMessage"] = 20,
		["mysql-async:request-data"] = 5,
		["mysql-async:request-server-status"] = 5,
		["mysql-async:request-table-schema"] = 5,
		["ghmattimysql:request-data"] = 5,
		["ghmattimysql:request-server-status"] = 5,
}

Config.Trigger = {
		{ eventName = "esx_policejob:handcuff", job = "police", "sheriff", "fbi", "ambulance", reason = "She tried to handcuff her without the police.",   },
		{ eventName = "esx_jailer:sendToJail", job = "police", "sheriff", "fbi", "ambulance", reason = "He tried to send her to jail without the police.",   },
		{ eventName = "police:cuffGranted", job = "police", "sheriff", "fbi", "ambulance", reason = "He tried to send her to jail without the police.",   },
		{ eventName = "esx_vehicleshop:putStockItems", job = "police", "sheriff", "fbi", "ambulance", reason = "Tried to put items in the safe without Car Dealer.",   },
		{ eventName = "esx_fbi:message", job = "police", "sheriff", "fbi", "ambulance", reason = "The bottom left tried to attack the announcements.",   },
		{ eventName = "esx_fbi:getStockItem", job = "police", "sheriff", "fbi", "ambulance", reason = "Tried to put items in the safe without FBI.",   },
		{ eventName = "esx_policejob:getStockItem", job = "police", "sheriff", "fbi", "ambulance", reason = "Tried to put items in the safe without Police.",   },
		{ eventName = "esx_sheriffjob:getStockItem", job = "police", "sheriff", "fbi", "ambulance", reason = "Tried to put items in the safe without Sheriff.",   },
		{ eventName = "lester:vendita", job = "police", "sheriff", "fbi", "ambulance", reason = "Money Printing Method 001.",  },
		{ eventName = "esx_communityservice:sendToCommunityService", job = "police", "sheriff", "fbi", "ambulance", reason = "The public acted.",},
}